### ISSUE TITLE
Allow stages to accept a list of strings instead of a maps

### ISSUE THREAD

**Issue by nshahan** [google/mono_repo.dart#150]
Right now the stages section of the top level mono_repo.yaml file is required to be a map where you have to provide the keys `name` and `if`. 

I had to write:
```
travis:
  stages:
    - name: analyze_and_format
      if: 'true'
    - name: unit_test
      if: 'true'
    - name: build
      if: 'true'
```

When all I want is:
```
travis:
  stages:
    - analyze_and_format
    - unit_test
    - build
```
