### ISSUE TITLE
Within a job, continuing running tasks for pkg N+1, even if pkg N fails

### ISSUE THREAD

**Issue by kevmoo** [google/mono_repo.dart#296]
```yaml
      - run: dart --version
      - uses: actions/checkout@v2
      # should have an ID here
      - id: mono_repo_pub_upgrade
        name: "mono_repo; pub upgrade --no-precompile"
        working-directory: mono_repo
        run: pub upgrade --no-precompile
      - name: "mono_repo; dartfmt -n --set-exit-if-changed ."
        if: "steps.mono_repo_pub_upgrade.conclusion == 'success'"
        working-directory: mono_repo
        run: dartfmt -n --set-exit-if-changed .
      - name: "mono_repo; dartanalyzer --fatal-infos ."
        if: "steps.mono_repo_pub_upgrade.conclusion == 'success'"
        working-directory: mono_repo
        run: dartanalyzer --fatal-infos .
      - id: test_pkg_pub_upgrade
        name: "test_pkg; pub upgrade --no-precompile"
        working-directory: test_pkg
        run: pub upgrade --no-precompile
       # should have an `if` here based on if checkout succeeds! Should still run if pkg:mono_repo fails
      - name: "test_pkg; dartfmt -n --set-exit-if-changed ."
        if: "steps.test_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_pkg
        run: dartfmt -n --set-exit-if-changed .
      - name: "test_pkg; dartanalyzer --fatal-infos ."
        if: "steps.test_pkg_pub_upgrade.conclusion == 'success'"
        working-directory: test_pkg
        run: dartanalyzer --fatal-infos .
```
