### ISSUE TITLE
Generate .github/dependabot.yaml

### ISSUE THREAD

**Issue by jonasfj** [google/mono_repo.dart#374]
```yaml
# .github/dependabot.yaml
version: 2
enable-beta-ecosystems: true # required while pub is in beta
updates:
  - package-ecosystem: "pub"
    directory: "path/to/package/"
    schedule:
      interval: "weekly"
 - ...
```

See also: https://github.blog/changelog/2022-04-05-pub-beta-support-for-dependabot-version-updates/
