### ISSUE TITLE
Allow integration with melos

### ISSUE THREAD

**Issue by GZGavinZhao** [google/mono_repo.dart#396]
[`melos`](https://github.com/invertase/melos/) is another tool for managing mono repos. However, I feel that `mono_repo` is better when generating readable/debuggable CI config in the least amount of typing. Therefore, we decided to use both `melos` and `mono_repo` for [our repo](https://github.com/angulardart-community/angular).

This, unfortunately, poses a problem: `melos` needs to be `dart pub global activate`-d and ran `melos bootstrap` to [link local packages using the `pubspec_overrides.yaml` file](https://melos.invertase.dev/configuration/overview#commandbootstrapusepubspecoverrides). If not, then analyzing and testing might fail. `mono_repo` provides no way of running arbitrary commands at the start of each CI job.

I hope we can either allow defining commands to be run at the start of each job, or add a `melos` config to `mono_repo.yaml`. When set to `true`, it will add a step to activate and bootstrap `melos` before any user-defined commands are run.

I have already [implemented](https://github.com/GZGavinZhao/mono_repo.dart/tree/add-melos) the second option in a basic way. If accepted I'd be glad to further polishing it!

**Comment by jakemac53** [comment]
Personally I would suggest just creating your own script under `tool`, which invokes melos and then mono_repo?

If we did want to support something like this I would probably just support running arbitrary commands, we don't want to be picking up a dependency on api of melos.

**Comment by natebosch** [comment]
> we don't want to be picking up a dependency on the api of melos.

+1

would https://github.com/google/mono_repo.dart/pull/382 be sufficient to solve this use case?

**Comment by blaugold** [comment]
I'm not very familiar with `mono_repo` so I've created an [example repo](https://github.com/blaugold/mono_repo_melos) to better understand how to integrate it with Melos.

It's possible to get it working with Melos, but it's not great:

```yaml
sdk:
  - stable

stages:
  - analyze:
      - command:
          - 'dart pub global activate melos'
          - 'dart pub global run melos bootstrap --scope a'
          - 'dart analyze'
  - format:
      - command:
          - 'dart pub global activate melos'
          - 'dart pub global run melos bootstrap --scope a'
          - 'dart format --output=none --set-exit-if-changed .'
  - test:
      - command:
          - 'dart pub global activate melos'
          - 'dart pub global run melos bootstrap --scope a'
          - 'dart test'
```

I don't think #382 would help all that much, since you would have to configure Melos for every job, if I understand the intent of the PR correctly. 

It would be optimal, if there was a way to replace the `pub upgrade` step with an arbitrary command. Even better, if the command gets the name of the current package in an environment variable.

If this was configurable in `mono_repo.yaml` for all jobs, it would make it really simple to set up Melos.
