### ISSUE TITLE
Support overriding dependabot updates

### ISSUE THREAD

**Issue by nikeokoronkwo** [google/mono_repo.dart#510]
I was trying to override the dependabot updates to run `"monthly"` rather than `"weekly"`,
```yaml
github:
  dependabot:
    updates:
      - package-ecosystem: "pub"
        directory: common
        schedule:
          interval: "monthly"
```
I noticed that the resulting `dependabot.yml` file contained both weekly and monthly updates (for the same package) rather than the user-defined option overriding the default option (i.e having only monthly updates)?

Is it possible to override the dependabot config for specific packages, and if not, is it possible to provide such options?
